import "./globals.css";
import { Inter } from "next/font/google";
import { Metadata } from "next";
import Sidebar from "../components/sidebar";
import { AnalyticsWrapper } from "../components/analytics";
import favicon from "../public/favicon.ico";

const inter = Inter({
    weight: "400",
    subsets: ["latin"],
    display: "swap",
    variable: "--font-inter",
});

export const metadata: Metadata = {
    title: {
        default: "Ved Kale",
        template: "%s | Ved Kale",
    },
    icons: {
        shortcut: "/favicon.ico",
    },
    robots: {
        index: true,
        follow: true,
        googleBot: {
            index: true,
            follow: true,
            "max-video-preview": -1,
            "max-image-preview": "large",
            "max-snippet": -1,
        },
    },
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={`text-white bg-[#121212] ${inter.variable}`}>
            <body className="antialiased max-w-4xl mb-40 flex flex-col md:flex-row mx-4 mt-8 md:mt-20 lg:mt-32 lg:mx-auto">
                <Sidebar />
                <main className="">
                    {children}
                    <AnalyticsWrapper />
                </main>
            </body>
        </html>
    );
}
