import "./globals.css";
import { Inter } from "next/font/google";
import { Metadata } from "next";
import Sidebar from "../components/sidebar";

const inter = Inter({
    weight: "400",
    subsets: ["latin"],
    display: "swap",
    variable: "--font-inter",
});

export const metadata: Metadata = {
    title: {
        default: "Ved Kale",
        template: "%s | Ved Kale",
    },
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={`text-white bg-[#121212] ${inter.variable}`}>
            <body className="antialiased max-w-4xl flex flex-col md:flex-row mx-32 mt-16">
                <Sidebar />
                <main className="">
                    {children}
                </main>
            </body>
        </html>
    );
}
