import './globals.css';
import { Inter } from '@next/font/google';
import { Metadata } from 'next';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: {
    default: "Ved Kale",
    template: "%s | Ved Kale"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`text-white bg-[#121212] ${inter.className}`}>
      <body>{children}</body>
    </html>
  )
}
